#!/bin/bash
destFile='check_jscoloration.js'
directory='jscoloration'
echo "//Do not edit, file generated by \"$0\"" > $destFile
echo 'window.filesToCheck = "'`ls $directory`'".split( /\s+/g );' >> $destFile

cat $destFile
