//Do not edit, file generated by "./check_jscoloration_build.sh"
window.filesToCheck = "applications.js browser.js jsinterp.cpp jsobj.cpp jsparse.cpp jstracer.cpp jsxml.cpp linecounting.js nsIEProfileMigrator.cpp nsSessionStore.js tabbrowser.xml".split( /\s+/g );
