<!DOCTYPE html>
<html>
    <head>
        <link rel="icon" href="/mxr.png" type="image/png">
        <title>Cross-Reference</title>
        <link rel='stylesheet' title='' href='/media/style/style.css' type='text/css'>
        <style type="text/css">
            body {{
            background-color: #fff;
            color: #000;
            }}
            a {{ color: #00e; }}
            a:visited {{ color: #551a8b; }}
            a:hover {{ color: #f00; }}
            .banner {{
            background-color: #000;
            width: 100%;
            border: 0px;
            }}
            .banner td {{
            padding: 0px;
            margin: 0px;
            }}
            .contentarea {{
            border: 0px;
            }}
            .note {{
            font-size: 70%;
            }}
            table.rootlist {{
            border: 1px solid black;
            width: 100%;
            background-color: #eee;
            }}
            table.rootlist td {{
            padding: 10px;
            }}
            table.rootlist h2 {{
            text-align: center;
            }}
            dl.rootlist dt {{
            font-size: 120%;
            }}
            dl.rootlist dt a {{
            font-weight: bold;
            }}
            dl.rootlist dd {{
            font-size: 70%;
            margin-bottom: 1em;
            }}
        </style>
    </head>
    <body>
        <table class="contentarea" width="500px" align="left">
            <tr>
                <td align="left" valign="top">
                    <table class="rootlist">
                        <tr>
                            <td>
                                <dl class="rootlist">
{0}
                                </dl>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </body>
</html>

