baseurl: {0}
bonsaihome: http://bonsai.mozilla.org
htmlhead: ./media/templates/template-head
htmltail: ./media/templates/template-tail
htmldir:  ./media/templates/template-dir
sourcehead: ./media/templates/template-source-head
sourcetail: ./media/templates/template-source-tail
sourcedirhead: ./media/templates/template-sourcedir-head
sourcedirtail: ./media/templates/template-sourcedir-tail
treechooser: ./media/templates/template-tree
treeentry: ./media/templates/template-tree-entry
revchooser: ./media/templates/template-rev
reventry: ./media/templates/template-rev-entry
identref: ./media/templates/template-ident-fileref

{1}
incprefix: /include
dbdir: {2}
glimpsebin: /usr/bin/glimpse