baseurl: {0}
bonsaihome: http://bonsai.mozilla.org
htmlhead: ./templates/template-head
htmltail: ./templates/template-tail
htmldir:  ./templates/template-dir
sourcehead: ./templates/template-source-head
sourcetail: ./templates/template-source-tail
sourcedirhead: ./templates/template-sourcedir-head
sourcedirtail: ./templates/template-sourcedir-tail
treechooser: ./templates/template-tree
treeentry: ./templates/template-tree-entry
revchooser: ./templates/template-rev
reventry: ./templates/template-rev-entry
identref: ./templates/template-ident-fileref

{1}
incprefix: /include
dbdir: {2}
glimpsebin: /usr/bin/glimpse